### ISSUE TITLE
[Proposal] Support cond, case and unless statements

### ISSUE THREAD

**Issue by lnr0626** [surface-ui/surface#107] opened 2020-08-11 22:12 UTC
Both of these would require a new AST type to represent the expressions, as well as some method of representing them in the template.

We could add a new element named `cond` and `case` to represent these types of expressions in the templates, a new directive named `:when` for representing cases/conditions, and a new directive `:expr` (this would probably need a better name) for `case` to represent the value that is being evaluated. As an example for `cond`:
```html
<cond>
  <template :when={{ @condition_1 }}>
    ...
  </template>
  <template :when={{ @condition_2 }}>
    ...
  </template>
  <template :when={{ true }}>
    ...
  </template>
</cond>
```

The above would be equivalent in LEEx to:
```elixir
<%= cond do %>
  <% @condition_1 -> %>
    ...
  <% @condition_2 -> %>
    ...
  <% true -> %>
    ...
<% end %>
```

and for `case`:
```html
<case :expr={{ @value }}>
  <template :when={{ value when is_boolean(value) }}>
    ...
  </template>
  <template :when={{ value when is_binary(value) }}>
    ...
  </template>
  <template :when={{ _ }}>
    ...
  </template>
</cond>
```

The above would be equivalent in LEEx to:
```elixir
<%= case @value do %>
  <% value when is_boolean(value) -> %>
    ...
  <% value when is_binary(value) -> %>
    ...
  <% _ -> %>
    ...
<% end %>
```

While the two types of statements can be implemented independently of each other, my suggestion for them both are similar; so I kept this as a single issue. If they diverge, we should probably split them into two issues.

**Comment by lnr0626** [comment] 2020-08-11 22:15
My reason for adding a new element instead of relying on a macro component for this is because each of the `templates` should have valid surface code within them, and this would result in slightly easier to process code.

**Comment by msaraiva** [comment] 2020-11-06 14:08
@lnr0626 with the addition of `<For>` and `<If>`, I believe we need to add some updates and answer a few questions.

### Updates

1. For consistency, we should have `<Cond>` and `<Case>` instead of `<cond>` and `<case>`
1. The root prop described in #191 would be a great fit for `<Case>`

### Questions

1. Will components also accept `:when` or only `<template>`?
1. If we're going to accept `<template :when={{...}}>`, should we also accept `<template :if={{...}}>` and `<template :for={{...}}>` and any other construct we might add in the future? Would it be ok to have different ways to achieve the same goal? Like `<template :if={{ expr }}>...</template>` == `<If condition={{ expr }}>...</If>`, or should we stick with just one approach? 
1. Can it be confusing to the user to have `<template>` serving as both, flow control and slotable content? Should we create another construct to be used instead of `<template>`?

**Comment by lnr0626** [comment] 2020-11-06 14:41
Agreed on both updates.

For the questions:

1 - I think it'd be easier to implement if we required a wrapper for each block in the case/cond body; but it'd be a slightly better UX if we allowed a single element to have this `:when` directive (i.e. if i only have a single html tag/component in the block, it'd be a lot to have to wrap that in a `<template>`. For simplicity though, we should probably start with requiring a wrapper component.

2 - We should try to stick with just one approach; imo having multiple approaches for the same thing makes it confusion to figure out how to do things when you're just starting out

3 - hm. it may be confusing; my original suggestion for `template` was because these seem similar to slotable content (if you look at it as each block is a potential slot, and the conditions determine which slot is actually used). However, I think it may be more natural to have another construct for this. The root prop would also be a good fit for specifying the condition. we could do something like:
```
<Case {{ @sort_order }}>
  <When {{ :ascend }}><#Icon name={{ :ascend_icon }} /></When>
  <When {{ :descend }}><#Icon name={{ :descend_icon }} /></When>
  <When {{ _ }}><#Icon name={{ :default_icon }} /></When>
</Case>
...
<Cond>
  <When {{ @sort_order == :ascend }}><#Icon name={{ :ascend_icon }} /></When>
  <When {{ @sort_order == :descend }}><#Icon name={{ :descend_icon }} /></When>
  <When {{ true }}><#Icon name={{ :default_icon }} /></When>
</Cond>
```

both would only accept a single, default slot, and in the transform validate that only `When` components are used. Then transform each `When` into the appropriate ast representation.

We'd likely want a different component for inside case/cond because the expressions accept different types.

**Comment by msaraiva** [comment] 2020-11-25 20:02
@lnr0626 I've been thinking lately about this issue and I believe that maybe we should try to come up with something more generic and flexible. This way we don't have to create one component for each existing construct. Here's a first idea (which I'm not sure is feasible or not yet) to start with:

```
<{{ case @some_prop do }}>
  <{{ nil -> }}>
    ...
  </>
  <{{ value -> }}>
    ...
  </>
</>

---

<{{ cond do }}>
  <{{ @some_prop == 1 -> }}>
    ...
  </>
  <{{ @some_prop == 2 -> }}>
    ...
  </>
</>

---

<{{ for item <- @items do }}>
  ...
</>

---

<{{ if @some_prop do }}>
  ...
<{{ else }}>
  ...
</>
```

The reason I'm keeping the `do` and `->` is so that we can infer when we should add the `end` or not.

**Comment by lnr0626** [comment] 2020-11-29 19:47
I think something like this makes sense, and I do think that specific syntax is feasible - the only thing that gives me pause is the else branch in:
```
<{{ if @some_prop do }}>
  ...
<{{ else }}>
  ...
</>
```

I like that it gives us a way to easily express `if`/`else` (as we don't really have that right now); but it breaks the html open/close tag pairs. This also makes it so that the interpolation is no longer always a complete expression.

Something like this would likely be simpler than trying to figure out how to do something like a root prop, and also feels less magical. We also need to figure out how this syntax would interact with the dynamic components suggested in #24

A prerequisite to any of this is adding the `Case`/`Cond` ast nodes, which I'm planning on looking into next time I find a few hours to put into it.

**Comment by msaraiva** [comment] 2020-11-30 18:33
> the only thing that gives me pause is the else branch

Yup. It also gives me the chills. I believe we have two options:

1. We just don't accept `else`. Period. This is probably fine as the user can still use `cond` instead to achieve the same result. It's just a bit more verbose.
2. Make the parser handle `<{{ else }}>` as a [void element](https://github.com/msaraiva/surface/blob/master/lib/surface/compiler.ex#L48-L62) just like it does for `<br>` and friends. This way we're "breaking" the html open/close tag pairs for sure but in a controlled way, hard coding what is accepted or not, which is exactly what we do for those existing void elements.

If adding `<{{ else }}>` brings to much complexity to the compiler, I believe we should go with `#1`.

> A prerequisite to any of this is adding the `Case/Cond` ast nodes, which I'm planning on looking into next time I find a few hours to put into it.

Awesome! ❤️

**Comment by msaraiva** [comment] 2020-12-03 14:30
Here's another suggestion that has the following benefits:

1. Differentiates real components from control-flow constructs.
1. Control flow-nodes have the same name as their related directive (if any). In fact, we should document them together, explaining that they can be used as a node or as a directive for a shorthanded version.
1. Interpolation keeps accepting only complete expressions (an issue previously raised by @lnr0626 ).

### For

```
<div :for={{ item <- @items }}>
  ...
</div>
```

Can also be written as the following if you need to wrap multiple nodes:

```
<:for {{ item <- @items }}>
  <div>
    ... 
  </div>
  <div>
    ... 
  </div>
</:for>
```

### If

```
<div :if={{ @some_prop }} >
  ...
</:div>
```

Can also be written as the following if you need to wrap multiple nodes:

```
<:if {{ @some_prop }} >
  <div>
    ... 
  </div>
  <div>
    ... 
  </div>
</:if>
```

### Case

```
<:case {{ @some_prop }}>
  <div :match={{ nil }}>
    ...
  </div>
  <div :match={{ value }}>
    ...
  </div>
</:case>
```

Can also be written as the following if you need to wrap multiple nodes:

```
<:case {{ @some_prop }}>
  <:match {{ nil }}>
    <div>
      ... 
    </div>
    <div>
      ... 
    </div>
  </:match>
  <:match {{ value }}>
    <div>
      ... 
    </div>
    <div>
      ... 
    </div>
  </:match>
</:case>
```

### Cond

```
<:cond>
  <div :when={{ @some_prop == 1 }}>
    ...
  </div>
  <div :when={{ @some_prop == 2 }}>
    ...
  </div>
</:cond>
```

Can also be written as the following if you need to wrap multiple nodes:

```
<:cond>
  <:when {{ @some_prop == 1 }}>
    <div>
      ... 
    </div>
    <div>
      ... 
    </div>
  </:when>
  <:when {{ @some_prop == 2 }}>
    <div>
      ... 
    </div>
    <div>
      ... 
    </div>
  </:when>
</:cond>
```

### Else*

```
<:if {{ @some_prop }} >
  <div>
    ... 
  </div>
<:else>
  <div>
    ... 
  </div>
</:if>
```

\* Again, I'm totally fine not adding `else` at all since we can use `cond` instead.

**Comment by lnr0626** [comment] 2020-12-04 16:31
I like that the directives and the proposed constructs mirror each other in that example. Having the colon prefix would also make it simpler to implement the attribute-less prop in the parser. I think the actual compiler support for something like would be fairly trivial - essentially having the compiler automatically build the `AST.Container` node with the single directive attached that we do inside the current `If`/`For` constructs.

The case/cond support has me thinking that we should have some way of allowing context sensitive directives (i.e. `:when` should only be allowed as a direct child of `:cond` and `:match` as a direct child of `:case`). I also have a few questions for these constructs (and for directives in general):

- do we want our users to be able to create their own directives?
- follow on: do we want users to be able to create their own constructs?
- should a construct always match 1:1 with a directive?
- should we enforce the colon prefix convention and log a warning/error when an attribute with a colon prefix is provided, but there's no matching directive?

**Comment by msaraiva** [comment] 2020-12-04 18:43
> we should have some way of allowing context sensitive directives (i.e. `:when` should only be allowed as a direct child of `:cond` and `:match` as a direct child of `:case`)

I agree.

> do we want our users to be able to create their own directives?

No. Maybe in the future but I have the feeling we should avoid that.

> do we want users to be able to create their own constructs?

Nope. I mean, the user can still create a macro or even a component to do something similar so I don't think we should add a third way to do that.

> should a construct always match 1:1 with a directive?

I don't think we should try to guarantee that. It's nice to have that symmetry for things like `:for` and `:if`, but for some of them, it doesn't make sense. For instance, I think `:cond` and `:case` should only be allowed as a constructs, otherwise it might be confusing to infer what is their effect on the host node, which is none. On the other hand, directives like `:when` and `:match` (maybe we should call it `:matching`) and the already mentioned `:for` and `:if`, act directly on the host node. So the golden rule could be: all of them can be used as constructs but their shorthand version as directives only exists if they have a direct effect on the node their are defined.

> should we enforce the colon prefix convention and log a warning/error when an attribute with a colon prefix is provided, but there's no matching directive?

We can do this for components. Maybe we already do? If not we should :) but for HTML tags we can't as they might be intended for some client lib like AlpineJS or similar so we need to bypass any validation a let them hit the browser. However, I think we should take the opportunity and discuss a possible general solution to avoid conflicts between client and server. My suggestion would be to allow users to define a optional prefix for constructs and directives along with a par of options to enable/disable static checks. Something like:

```elixir
defmodule MyComponent do
@moduledoc """
This component uses a JS lib that conflicts with Surface's syntax.
"""

use Surface.Component, 
  directive_prefix: "s", # default is "" (no prefix)
  disable_checks: [:unknown_directive] # default is enabled. Using a list in case we want to have more checks

def render(assigns) do
  ~H"""
  <:for {{ item <- @items}}>
     <div s:if={{ item == :whatever }}>
      ...
     </div>
  </:for>
  """
end
```

Both options could be also be set globally in `config.exs`.

**Comment by zachdaniel** [comment] 2020-12-04 19:01
This all looks good to me, but I do think it could be better to have all directives always go to surface, and require a set prefix for non-surface directives that gets stripped out at the end. Then no configuration would be required. I have no idea what that set prefix would look like, so this is a total shot in the dark but `browser:directive=...` seems expressive-ish to me. I'm new to surface/these kinds of tooling though, so take it with a grain of salt :)

**Comment by msaraiva** [comment] 2020-12-05 11:06
Hey @zachdaniel!

> I do think it could be better to have all directives always go to surface, and require a set prefix for non-surface directives that gets stripped out at the end

I think this is somehow the current behaviour. Although we don't have a specific prefix to do that, the client libs usually provide one. For instance, in Alpine.js, the `:attribute` notation is just a shorthand for `x-bind:attribute` so, at least for Alpine, we have a way out to avoid the conflict.

Maybe this is a non-issue and we should not address it right now. We can wait for some feedback from people using Alpine to make a better decision.

So Alpine people. Is the directive syntax using `:` somehow confusing when using Surface + Alpine.js?

**Comment by devilcoders** [comment] 2020-12-05 11:17
@msaraiva I'm just starting out with Alpine but I think there may be a conflict. I think we can avoid conflict on a technical level, meaning there will be no issues in the browser for example. But we can have conflict and problems in editor (think highlight, code completion, etc.) I would prefer to have those directive out of HTML tags. That will make it much easier with an editor.

Having directives separated from HTML markup will also make it more visible where is the logic applied. It's kind of easy to miss the directives right now when they look like HTML attributes.

**Comment by msaraiva** [comment] 2020-12-05 12:13
@devilcoders those are very good points to consider. Thanks! 👍

**Comment by msaraiva** [comment] 2020-12-08 13:02
So it seems so far we have the following suggestions to avoid syntax conflicts between `Surface` and client libs like `Alpine.js`:

### 1. Allow setting an optional prefix for directives

```elixir
defmodule MyComponent do
  use Surface.Component, directive_prefix: "s"

  def render(assigns) do
    ~H"""
    <div s:if={{ item == :whatever }}>
      ...
    </div>
    """
  end
end
```

Anything else starting with `:` will be ignored by Surface allowing the client lib to handle it.

Note: The prefix could also be set globally in `config.exs`.

### 2. Add a prefix to indicate that the attribute will be handled by the client

The prefix will then be ignored and stripped by Surface to allow the client lib to handle it.

```elixir
defmodule MyComponent do
  use Surface.Component

  def render(assigns) do
    ~H"""
    <div browser:if="whatever the client needs">
      ...
    </div>

    or maybe:

    <div client:if="whatever the client needs">
      ...
    </div>

    or maybe:

    <div _:if="whatever the client needs">
      ...
    </div>

    Any other suggestion???
    ...
    """
  end
end
```

### 3. Remove support for directives

This way any directive will have to be converted into an independent node so instead of:

```
<div :if={{ condition }}>
    ...
</div>
```

we'll always have to use:


```
<:if {{ condition }}>
  <div>
    ...
  </div>
</:if>
```

One problem I see with this last approach is how to replace `:let`, `:props` and `:attrs` nicely.

More suggestions are welcome!

**Comment by MrYawe** [comment] 2020-12-08 17:03
The following a **personal** user opinion and I may miss a lot of technical constraint (like the compiler).

I like this Vue.js philosophy :
> any valid HTML is also a valid Vue template, and this leads to a few advantages of its own:
> * For many developers who have been working with HTML, templates feel more natural to read and write. The preference itself can be somewhat subjective, but if it makes the developer more productive then the benefit is objective.
> * HTML-based templates make it much easier to progressively migrate existing applications to take advantage of Vue’s reactivity features.
> * It also makes it much easier for designers and less experienced developers to parse and contribute to the codebase.
> ...
https://vuejs.org/v2/guide/comparison.html#HTML-amp-CSS

While Surface and its context are obviously different than Vue I think that it might make sense to embrace this as close as we can. That would discard option `3.` directly and make option `2.` less ideal.

Also I feel that a conflict is "rare enough" to make `1.` more than a viable long-term solution.

I would love to read more personal opinions on this 😄

**Comment by paulstatezny** [comment] 2020-12-08 19:29
I agree with @MrYawe 's assessment. To be clear, option `1.` would be backwards compatible with the current API, correct?

**Comment by devilcoders** [comment] 2020-12-08 20:01
I would prefer **option 3** for a specific reason, I already described. I think having logic elements outside the markup is always a better solution. This way it's much easier to visually distinguish markup from logic. And I would assume having syntax highlight in the editor may be easier as this conditions will not mix with attributes.

Imagine something like this:

```vue
<div class="border border-indigo-900 p-4 rounded text-lg font-bold text-center text-indigo-800 antialiased" aria-label="Product Card" s:if={{ @is_availabe }}>
  {{ @content }}
</div>
```

Comparing with this:

```vue
<:if {{ @is_available }}>
   <div class="border border-indigo-900 p-4 rounded text-lg font-bold text-center text-indigo-800 antialiased" aria-label="Product Card" s:if={{ @is_availabe }}>
    {{ @content }}
  </div>
</:if>
```

Or even this:

```vue
{{ if @is_available }}
   <div class="border border-indigo-900 p-4 rounded text-lg font-bold text-center text-indigo-800 antialiased" aria-label="Product Card" s:if={{ @is_availabe }}>
    {{ @content }}
  </div>
{{ end }}
```

One of the reasons I really love **React** is that you can easily split JS part from JSX, visually. And editor syntax highlight will help you to do this. For a change, if we're talking about custom syntax, here are few examples with a similar way of splitting logic from markup:

###### [Svelte](https://svelte.dev/tutorial/if-blocks)

```svelte
{#if user.loggedIn}
	<button on:click={toggle}>
		Log out
	</button>
{/if}
```

###### [Marko](https://markojs.com/docs/conditionals-and-lists/)

```marko
<if(user.loggedOut)>
    <a href="/login">Log in</a>
</if>
```

###### [Ember](https://guides.emberjs.com/release/components/conditional-content/)

```handlebars
{{#if condition}}
  {{!-- some content --}}
{{/if}}
```

People, used to Angular, Vue, Riot may prefer other options more. It all depends on what we're used to. For me, when I'm coming to unknown code, the ability to quickly visually scan code is a huge speed boost.

**Comment by paulstatezny** [comment] 2020-12-08 20:31
@devilcoders I think you have a great point. If it were removed from being a attribute on the HTML elements, we completely sidestep the problem of confusing which system handles a given directive.

I could see this being a big win for readability. Forgive my fickleness, but I think I just changed my vote.

**Comment by msaraiva** [comment] 2020-12-08 20:57
> I agree with @MrYawe 's assessment. To be clear, option `1.` would be backwards compatible with the current API, correct?

@paulstatezny Correct. The default would be `no prefix`.

> here are few examples with a similar way of splitting logic from markup:
> 
> Svelte
> ...


@devilcoders thanks for you inputs again. Just to make it clear, the proposal keeps the ability to use:

```
<:if {{ condition}}>
...
</:if>
```

or any other flow-control construct like `for`, `case`, etc. The problem is that even if we removed all those constructs from the list of accepted directives, we still need to find a way to handle `:on-*`, `:let`, `:props` and `:attrs`.

Svelte, since you mentioned, still makes extensive use of directives. A few examples:

  * https://svelte.dev/tutorial/event-modifiers
  * https://svelte.dev/tutorial/classes
  * https://svelte.dev/tutorial/slot-props

That means the "splitting logic from markup" is not 100% true. There is logic defined as custom attributes too.

So it seems that we need directives anyway, which brings us back to the original problem. How to avoid conflicts with those few remaining directives? 

I'm pretty sure those conflicts are not a real problem today and we don't have to address this problem right now either, but we need to make sure we have a way out when it does, otherwise, we may have to change the syntax substantially in the future because of some new JS framework (remember that frontend stuff changes all the time), which could be a pain for most users. 

I'm open to suggestions, including removing all directives, as long as we have a feasible alternative to handle things like `:on-*`, `:let`, `:props` and `:attrs`

**Comment by devilcoders** [comment] 2020-12-09 08:47
@msaraiva You are correct. My main concern was to avoid conditionals as directives if possible. But regarding other directives and possible conflicts - Alpine directives starts with either `x-` or `@`. I think the only one exception is `:key` in `x-for` loop directive.

One way to avoid conflict may be to use `attr`. Alpine will only deal with what is actually rendered in the browser. This may impact editor support for intellisence though... Hard to say without going deep and trying all cases.

**Comment by msaraiva** [comment] 2020-12-09 16:11
@devilcoders I think we're getting somewhere. One thing we could do, after we have all statement nodes available, is to start depending less on directives. 

Let's take a look at the list of all directives grouped by type and since directive conflicts can only happen in HTML tags (not in components), let's consider only:

Tag `<slot>`:

  * :props
  * :if
  * :for

Tag `<template>`:

  * :let

All other HTML Tags:

  * :attrs
  * :on-*
  * :show
  * :if
  * :for

If we replaced `<slot>` and `<template>` with component counterparts, like `<Slot>` and `<Template>` we'll have only the following directives left:

  * :attrs
  * :on-*
  * :show
  * :if
  * :for

And if we decide to remove statements, we'd end up with only:

  * :attrs
  * :on-*
  * :show

Regarding statements, I agree that using `for` as a directive doesn't add much and potentially makes the code harder to read so I have no problem removing it. However, `if` has shown being quite useful and readable, IMO, especially because the expressions are usually short and most of the time is just something like `:if={{ @open }}`. Having said that, I can still change my mind and remove it for consistency.

So, what are your thoughts if we:

1. Add the statements `<:for>`, `<:if>`, `<:case>` and all other previously proposed to the template language.

1. Add `<Slot>` and `<Template>` to be used instead of `<slot>` and `<template>`

1. Remove `:for` and maybe also `:if` from the list of directives

1. Wait for an eventual conflict to be reported. When that happens, if that happens, accept an optional prefix for the remaining directives.

/cc @lnr0626 and @Malian

**Comment by devilcoders** [comment] 2020-12-09 16:21
@msaraiva I agree. That sounds very reasonable at this point. Also, I like having `<Slot />` and `<Template />` - making it visible that those are Surface, not HTML part of code.

To be honest, I get used to `:if` directive myself already. But it all depends on how you code. As _frontend-first_ developer, and having many years of vanilla HTML/CSS experience, I try writing my code to be very readable, but it's not always the case. I saw a terrible mess can come out of templates if markup language allow it in the first place. That's why I'm concerned about NOT allowing something potentially confusing.

So, to answer your questions:

1. Agree
2. Agree
3. I'm in favor of removing them
4. Agree

**Comment by lnr0626** [comment] 2020-12-09 17:09
We'll likely want to move to a `<Slot>` and `<Template>` directive regardless as currently any use of those is treated as being for surface, and it should simplify the implementation of slot a bit.

The one other directive is `:debug`, which would also fit as a construct/statement element/w.e. we're calling these things.

Removing `:for` as a directive also makes the order of ops between `:if` and `:for` much clearer and explicit. However, I'm not a fan of removing `:if` though as the new syntax is more heavy weight than what we currently have.

Based on this direction, I assume that we would not expose `:matching` and `:when` as directives, and instead keep them as elements?

For the path forward you suggested:

1. Agreed
2. Agreed
3. 
    * `:for` - I *personally* prefer the for directive's lightweight syntax when there's only a single element; however, am not against removing it based on the points raised in this discussion
    * `:if` - I do not agree with removing the if directive
4. Agreed

**Comment by msaraiva** [comment] 2020-12-17 14:23
@lnr0626 thanks for your inputs. I think we could keep `:if`, `:matching` and `:when` as shorthands. I also think we'll need to add at least two compile-time validations:

1. `:matching` and `:when` can only exist as direct nodes of a `:case` and `cond`, respectively.
2. `:if`, `:matching` and `:when` are mutually exclusive.

**Comment by lnr0626** [comment] 2020-12-17 14:43
That sounds good to me!

As an alternative option for bullet 2, we _could_ support `:if` and `:matching`, and `:if` and `:when` on the same element as there is a somewhat natural order of precedence (given that `:matching` and `:when` can only be direct nodes of `:case` and `:cond` respectively, they would be applied last and wrap the results of everything else. (because of bullet 1, `:matching` and `:when` would be mutually exclusive)

**Comment by olivermt** [comment] 2021-02-24 18:37
I do not think we should remove :if, it's a great directive.

I am pretty sure that we should not have matching (negative if) or when (redundant if).
I am 100% in agreeance that we should get rid of :for, because I think it makes for sloppy code readability wise and I really disliked angular etc big usage of those directives.

I am 100% sure we should have a modifier variant of if that keeps inner content as discussed on slack.

```
<div :if.keepinner={{@value}}>
this is not deleted, but if @value is false the outer div disappears
</div>
```

A bunch of CSS libs depend on optional wrapping elements and its a good pattern in general if you want to do components that wrap based on the shape of the props and you dont want huge trees of If or weird Raw usage.

**Comment by lnr0626** [comment] 2021-02-24 18:40
> I am 100% sure we should have a modifier variant of if that keeps inner content as discussed on slack.

Is rather have something like an `:unwrap` directive than an if modifier - imo its intent is far clearer than `.keepinner`

**Comment by olivermt** [comment] 2021-02-24 18:42
I would not have the faintest clue what `:unwrap` would do from the name, but I also absolutely don't care what its called if I can have the feature and not have Raw, raw() and other variants around in my code :)

**Comment by msaraiva** [comment] 2021-04-19 14:51
Closing this in favour of https://github.com/surface-ui/surface/issues/340.

**Closed by msaraiva** 2021-04-19 14:51 UTC
Labels: Discussion, on hold
