### ISSUE TITLE
Error in `formsForRecovery`

### ISSUE THREAD

**Issue by Victoria91** [surface-ui/surface#582] opened 2022-03-31 13:36 UTC
Hello and thanks for the library!
After update to surface 0.7.3 we founded an error on form submit (uses [form-request-submit-polyfill](https://www.npmjs.com/package/form-request-submit-polyfill))
```js
import "form-request-submit-polyfill";
const FormSubmitter = {
  mounted() {
    this.handleEvent("save", () => {
       this.el.querySelector("form").requestSubmit();
    });
  },
};

export { FormSubmitter };
```
the error raises later [on](https://github.com/phoenixframework/phoenix_live_view/blob/1d706465000e5c3821a3a37c2c5531ae0f0cd074/priv/static/phoenix_live_view.js#L3124) :

```
Uncaught DOMException: Failed to execute 'querySelector' on 'DocumentFragment': 'form[id="phx-FuF1I-QOjSGTu-lD-13-0"][phx-change="[["push",{"event":"search","target":13}]]"]' is not a valid selector.
```
As I reserched it started to fail on [this commit](https://github.com/surface-ui/surface/commit/6aab9139c66bc242be6d6c58d1c2e7ad646504aa). 

Can you advise how to fix this? 

## Environment
Surface: v0.7.3
LiveView: v0.17.7
Elixir: v1.13.3-otp-24

Thanks!

**Comment by miguel-s** [comment] 2022-04-05 16:59
Hi @Victoria91!

Thanks for opening the issue. I am not able to reproduce the error you describe, could you please share a full example or even create a repo that triggers this issue?

**Comment by Victoria91** [comment] 2022-04-14 14:35
@miguel-s Thanks for reply, done https://github.com/Victoria91/surface-error
While extracting code producing error I found out that there is another error ocurring before the error I've mentioned, so maybe this is the reason. 

Steps to reproduce: 
- visit "/"
- click on dropzone, select file|
- press submit button

In master branch everything works fine in [surface-0.7.3](https://github.com/Victoria91/surface-error/tree/surface-0.7.3) branch the error `no uploads have been allowed on LiveView named SurfaceErrorWeb.HomeLive` will raise. Also there is a test that will fail in new branch. Thanks!

**Comment by miguel-s** [comment] 2022-04-21 18:17
Hi @Victoria91 

> While extracting code producing error I found out that there is another error ocurring before the error I've mentioned, so maybe this is the reason.

Yes I've seen this happen, too. A prior (unrelated) error will sometimes trigger that error message, which is confusing. Did fixing that other error remove the `Uncaught DOMException: Failed to execute 'querySelector'...` error message?

> In master branch everything works fine in [surface-0.7.3](https://github.com/Victoria91/surface-error/tree/surface-0.7.3) branch the error no uploads have been allowed on LiveView named SurfaceErrorWeb.HomeLive will raise.

This looks related to this LiveVIew issue https://github.com/phoenixframework/phoenix_live_view/issues/1893. Until that issue is addressed adding `phx-target={@myself}>` to your form should make it work again.

**Comment by Malian** [comment] 2022-04-27 08:03
@miguel-s I have encountered the same error on two of my projects. I also had to add the event into the `opts` to "fix" the issue.

This is the Surface code with a Surface event and a regular phx event:
```html
<Form
    for={@changeset}
    change="validate"
    opts={
      id: "my-id",
      phx_submit: "save",
      phx_target: @myself
    }
/>
```
and the generated HTML
```html
<form
  action="#"
  method="post"
  id="my-id"
  phx-change='[["push",{"event":"validate","target":1}]]'
  phx-submit="save"
  phx-target="1"
>
 ...
</form>
```

I'll try to investigate next week.

**Comment by Victoria91** [comment] 2022-07-27 19:42
> Hi @Victoria91
> 
> > While extracting code producing error I found out that there is another error ocurring before the error I've mentioned, so maybe this is the reason.
> 
> Yes I've seen this happen, too. A prior (unrelated) error will sometimes trigger that error message, which is confusing. Did fixing that other error remove the `Uncaught DOMException: Failed to execute 'querySelector'...` error message?
> 
> > In master branch everything works fine in [surface-0.7.3](https://github.com/Victoria91/surface-error/tree/surface-0.7.3) branch the error no uploads have been allowed on LiveView named SurfaceErrorWeb.HomeLive will raise.
> 
> This looks related to this LiveVIew issue [phoenixframework/phoenix_live_view#1893](https://github.com/phoenixframework/phoenix_live_view/issues/1893). Until that issue is addressed adding `phx-target={@myself}>` to your form should make it work again.

Thanks, it solved the problem!

**Comment by Malian** [comment] 2022-07-29 16:11
My error was definitely linked to this one from LV: https://github.com/phoenixframework/phoenix_live_view/issues/1850

As the issue no longer seems to concern anyone, I am closing the file. Please feel free to reopen it if the error reappears.

**Closed by Malian** 2022-07-29 16:11 UTC
