### ISSUE TITLE
Form component event not sent to parent liveview

### ISSUE THREAD

**Issue by njouanin** [surface-ui/surface#372] opened 2021-05-06 03:41 UTC
I'd like a form component to send it's parent liveview an event on submit so the liveiw can handle its stuff with it.

Form component code is :
```
defmodule Component do
    use Surface.LiveComponent

    alias Surface.Components.LiveRedirect
    alias Surface.Components.Form
    alias Surface.Components.Form.{Field, Label, EmailInput, PasswordInput}

    data changeset, :changeset, default: FormData.changeset(%FormData{})
    prop submit, :event, required: true
    prop class, :css_class

    def render(assigns) do
      ~H"""
      <Form for={{ @changeset }} change="validate" submit={{ @submit }} class={{ @class }}>
        <Field name={{:email}} class="form-control w-1/2">
          <Label class="label"><span class="label-text">Email</span></Label>
          <EmailInput class="input input-bordered flex-grow"/>
        </Field>
        <Field name= {{ :password }} class="form-control w-1/2">
          <Label class="label"><span class="label-text">Password</span></Label>
          <PasswordInput class="input input-bordered flex-grow"/>
        </Field>
        <div class="card-actions w-1/2 mt-4">
          <button type="submit" class="btn btn-primary flex-grow">Login</button>
        </div>
        <div class="mt-2">
          <p><small>Don't have an account yet? <LiveRedirect to="/" class="link">Register now</LiveRedirect></small></p>
        </div>
      </Form>
      """
    end

    def handle_event("validate", %{"form_data" => form_data} = _params, socket) do
      {:noreply, assign(socket, changeset: FormData.validate(form_data))}
    end
  end
```

It's called from live view as:
```
<LoginForm.Component id="login_form" class="grid flex-grow card rounded-box place-items-center p-4" submit="submit_login"/>`
```

When running the event is not sent to the view. Instead, an error appears on the console saying the event if not handled inside the component:

```
[error] GenServer #PID<0.872.0> terminating
** (FunctionClauseError) no function clause matching in ScubananaWeb.Components.LoginForm.Component.handle_event/3
    (scubanana 0.1.0) lib/scubanana_web/components/auth/login_form.ex:66: ScubananaWeb.Components.LoginForm.Component.handle_event("submit_login", %{"_csrf_token" => "STEcNBYXARoIXRcKAiI-A2R3IgU4ODxhxcQeNvenBh_fqvuoU9hFkzp9", "form_data" => %{"email" => "pipo@grer.com", "password" => "njnkilk"}}, #Phoenix.LiveView.Socket<assigns: %{__context__: %{}, __surface__: %{provided_templates: [], slots: %{default: %{size: 0}}}, changeset: #Ecto.Changeset<action: :insert, changes: %{email: "pipo@grer.com", password: "njnkilk"}, errors: [], data: #ScubananaWeb.Components.LoginForm.FormData<>, ...>, class: ["grid", "flex-grow", "card", ...], flash: %{}, id: "login_form", myself: %Phoenix.LiveComponent.CID{...}, ...}, changed: %{}, endpoint: ScubananaWeb.Endpoint, id: "phx-Fnw5YvsA_onOLggh", parent_pid: nil, root_pid: #PID<0.872.0>, router: ScubananaWeb.Router, view: ScubananaWeb.Live.Auth, ...>)
    (phoenix_live_view 0.15.5) lib/phoenix_live_view/channel.ex:532: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4
    (telemetry 0.4.3) /home/nico/Dev/elixir/scubanana/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
    (phoenix_live_view 0.15.5) lib/phoenix_live_view/diff.ex:194: Phoenix.LiveView.Diff.write_component/5
    (phoenix_live_view 0.15.5) lib/phoenix_live_view/channel.ex:467: Phoenix.LiveView.Channel.component_handle_event/6
    (stdlib 3.14.1) gen_server.erl:689: :gen_server.try_dispatch/4
    (stdlib 3.14.1) gen_server.erl:765: :gen_server.handle_msg/6
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: %Phoenix.Socket.Message{event: "event", join_ref: "4", payload: %{"cid" => 1, "event" => "submit_login", "type" => "form", "value" => "_csrf_token=STEcNBYXARoIXRcKAiI-A2R3IgU4ODxhxcQeNvenBh_fqvuoU9hFkzp9&form_data%5Bemail%5D=pipo%40grer.com&form_data%5Bpassword%5D=njnkilk"}, ref: "25", topic: "lv:phx-Fnw5YvsA_onOLggh"}
State: %{components: {%{1 => {ScubananaWeb.Components.LoginForm.Component, "login_form", %{__context__: %{}, __surface__: %{provided_templates: [], slots: %{default: %{size: 0}}}, changeset: #Ecto.Changeset<action: :insert, changes: %{email: "pipo@grer.com", password: "njnkilk"}, errors: [], data: #ScubananaWeb.Components.LoginForm.FormData<>, valid?: true>, class: ["grid", "flex-grow", "card", "rounded-box", "place-items-center", "p-4"], flash: %{}, id: "login_form", myself: %Phoenix.LiveComponent.CID{cid: 1}, submit: %{name: "submit_login", target: :live_view}}, %{changed: %{}}, {259600609530064383679246163127329272028, %{0 => {312990514172168885060868392144259250070, %{1 => {35623172234797110444221597802535427506, %{0 => {255024400209805022487295997577755011759, %{0 => {209471766889125956988027049871984872194, %{0 => {32859353505857416172504484118409253708, %{1 => {35623172234797110444221597802535427506, %{0 => {10213661906507200381920705888882159500, %{0 => {191820519903937720872913227728913652351, %{0 => {225504868675489498177704610619311130714, %{0 => {25981701378987822305221321855520946747, %{0 => {35623172234797110444221597802535427506, %{0 => {69486023734767344234967263443666505224, %{0 => {212725133207165191245201631229551845460, %{1 => {...}}}}}}}}}}}, 1 => {108748831942311958983860759464981506879, %{0 => {25981701378987822305221321855520946747, %{0 => {35623172234797110444221597802535427506, %{0 => {69486023734767344234967263443666505224, %{0 => {193530162047916805050581505098736708261, %{}}}}}}}}}}}}}}}}}}, 1 => {32859353505857416172504484118409253708, %{1 => {35623172234797110444221597802535427506, %{0 => {10213661906507200381920705888882159500, %{0 => {293659014233432738103200002026886094709, %{0 => {225504868675489498177704610619311130714, %{0 => {25981701378987822305221321855520946747, %{0 => {35623172234797110444221597802535427506, %{0 => {69486023734767344234967263443666505224, %{0 => {212725133207165191245201631229551845460, %{...}}}}}}}}}}, 1 => {243189939379722356416779420020871189030, %{0 => {25981701378987822305221321855520946747, %{0 => {35623172234797110444221597802535427506, %{0 => {69486023734767344234967263443666505224, %{0 => {329056799441769299817063097777886337571, ...}}}}}}}}}}}}}}}}}, 5 => {9639511254798209485094537076720159810, %{4 => {238220134368232668558468651810674527735, %{}}}}}}}}}}}}}}}}, %{ScubananaWeb.Components.LoginForm.Component => %{"login_form" => 1}}, 2}, join_ref: "4", serializer: Phoenix.Socket.V2.JSONSerializer, socket: #Phoenix.LiveView.Socket<assigns: %{__context__: %{}, __surface__: %{}, flash: %{}, live_action: :index}, changed: %{}, endpoint: ScubananaWeb.Endpoint, id: "phx-Fnw5YvsA_onOLggh", parent_pid: nil, root_pid: #PID<0.872.0>, router: ScubananaWeb.Router, view: ScubananaWeb.Live.Auth, ...>, topic: "lv:phx-Fnw5YvsA_onOLggh", transport_pid: #PID<0.868.0>, upload_names: %{}, upload_pids: %{}}
```

**Comment by miguel-s** [comment] 2021-05-06 06:15
Thanks for opening the issue @njouanin!

Here a summary of my conversation with @msaraiva:

#### Troubleshooting

1. What is printed in the console if you inspect the event: `submit={{ IO.inspect(@submit) }}`?
`%{name: "submit", target: :live_view}`

2. What is the generated HTML for the `<Form>` component in the browser?
`<form action="#" method="post" phx-change="validate" phx-submit="submit" phx-target="1" data-phx-component="1" id="phx-FnxCZ-aWVwinlwBF-1-0">`

#### Problem

The `phx-target="1"` is not supposed to be generated when `target: :live_view` is passed.

#### Investigation

The problem does not exist when using `:on-submit`. However, any component passing the event as opts will not have the same handling 

We need to treat the event the same way we do when using the directive https://github.com/surface-ui/surface/blob/master/lib/surface/directive/events.ex#L105-L123

The `events_to_opts` actually calls `Surface.event_to_opts` which should treat it properly but it doesn't https://github.com/surface-ui/surface/blob/master/lib/surface.ex#L236-L246

**Comment by miguel-s** [comment] 2021-05-06 06:52
@msaraiva found the cause and it seems it's a limitation with LiveView.

The component is passing two events with different targets to the `<Form>`
1. `submit={{ @submit }}` with `target: :live_view`
2. `change="validate"` with `target: @myself`
 
The second event adds `phx-target="1"` to the `<form>` html element, which then gets also used by the first event.
I don't think there's much we can do to support mixes targets 🤔 

@njouanin seems that until we figure something out you'll have to choose to either handle all events in the component or in the liveview.

A pattern that has worked for me in the past:

1. Handle all events in your component end send the data to your liveview
```elixir
def handle_event("submit", %{"form_data" => form_data}, socket) do
  send(self(), {:submit, form_data})
  {:noreply, socket}
end
```

2. Handle the info in your liveview
```elixir
def handle_info({:submit, form_data}, socket) do
  IO.inspect(form_data)
  {:noreply, socket}
end
```

**Comment by msaraiva** [comment] 2021-05-06 13:02
Oh god, yes. This is an annoying Liveview limitation. Thanks @miguel-s for tracking it down. 

To make it worse, it's a design decision, not a bug. 🤷‍♂️ 

@njouanin as you can see here https://github.com/phoenixframework/phoenix_live_view/pull/669, I tried my best to convince both, José and Chris that we should allow setting different targets for different events. It's crystal clear, IMO. Unfortunately, my persuasion skills were not enough to convince them and that nice, very useful PR was closed without any further justification.

As I'm still convinced that LV shouldn't have this limitation just for the sake of it (as you can see in the thread, there are no drawbacks in having it), I believe you should try to reopen the PR (or probably just comment there) and present your use case. You don't even have to present the code. You just want to validate the form in your component but submit it to the parent. That's a totally valid use case and I can't see any reason LV has to force the user to "find another way" of doing something as trivial as that.

@miguel-s one thing we could do is to add a warning whenever we identify different targets. We could even point it to the PR so the user can have a whole picture of the issue. For components using `events_to_opts` that would be quite easy to do. Not sure how easy it would be when using `:on-*` though. Anyway, let's see if @njouanin have any luck reopening the PR. If not, we can move on with the warning idea. 

I'm closing the issue for now as there's nothing we can do about, except wait.

**Closed by msaraiva** 2021-05-06 13:02 UTC

**Comment by Malian** [comment] 2021-05-06 13:38
@msaraiva @miguel-s @njouanin Trust me or not, but yesterday I had the exact same use case. I would like to validate the form in the component but I would like to handle the submit in the parent live view.

**Comment by miguel-s** [comment] 2021-05-06 13:43
@Malian I believe you 😂 I have a similar use-case with a multi-step form. Each step is a component that validates its part and then sends the data to the parent form (that's how I got to the solution I posted above).

**Comment by msaraiva** [comment] 2021-05-06 13:50
@Malian and @miguel-s I believe you both :)

You may also try to comment on the mentioned PR. Who knows?🤞

**Comment by njouanin** [comment] 2021-05-06 16:00
Thank you all for your help. The proposed workaround works fine.
As you said it makes sense to me to have the liveview handle submit from the form component submit, and let the the component handle fields validation.
