### ISSUE TITLE
LV 0.17.11 - cannot convert component

### ISSUE THREAD

**Issue by maennchen** [surface-ui/surface#624] opened 2022-07-19 12:36 UTC
## Describe the bug

Since updating to `phoenix_live_view` `0.7.11` from `0.7.10`, I get the following error on various components:

```
** (ArgumentError) cannot convert component HygeiaWeb.AddressForm with id "address" to HTML.

A component must always be returned directly as part of a LiveView template.

For example, this is not allowed:

    <%= content_tag :div do %>
    <.live_component module={SomeComponent} id="myid" />
    <% end %>

That's because the component is inside `content_tag`. However, this works:

    <div>
    <.live_component module={SomeComponent} id="myid" />
    </div>

Components are also allowed inside Elixir's special forms, such as
`if`, `for`, `case`, and friends.

    <%= for item <- items do %>
    <.live_component module={SomeComponent} id={item} />
    <% end %>

However, using other module functions such as `Enum`, will not work:

    <%= Enum.map(items, fn item -> %>
    <.live_component module={SomeComponent} id={item} />
    <% end %>
```

The affected components look very normal to me, so I don't know what exactly triggers the issue.

If I had to guess, this is the commit that caused it: https://github.com/phoenixframework/phoenix_live_view/commit/25664f5edadbb4671a416dcb9bd8fdfe1f40cffb

This is probably not a surface issue, but rather a live view one. Since I do not have the same issue in other projects not using surface,  I decided to open the issue here. I'll happily close & open an issue directly in LV if that was the wrong decision.

## How to reproduce it
1. https://github.com/jshmrtn/hygeia/pull/1511
2. See actions - https://github.com/jshmrtn/hygeia/runs/7405108296?check_suite_focus=true
3. Example Component triggering the issue: https://github.com/jshmrtn/hygeia/blob/main/lib/hygeia_web/live/address_form.ex

## The behavior you expected

No error

## Your Environment

* Surface: `0.7.4`
* LiveView: `0.7.11`
* Elixir: `1.13.4`

**Comment by elliotb** [comment] 2022-07-19 12:53
Thank you for submitting this issue, I intended to raise it following the discussion in the Slack channel at https://elixir-lang.slack.com/archives/C01220C92QM/p1657692885106739

We're also seeing this with a live component that renders a single `Select` component as it's only element.

e.g. where the render function of the (stateful) live component is:

```
def render(assigns) do
    ~F"""
    <Select options={@schools} class={["input", "pl-3", "pr-10", "py-2"] ++ @class} prompt="Select a school" />
    """
  end
```

and the usage of it is from within another stateful live component:

```
    <Form for={@changeset} change="change" class="grid grid-cols-2 md:grid-cols-12 gap-2" opts={id: "filter-form"}>
        <Field name={:pupil_id} class="hidden"><HiddenInput /></Field>

        <Field name={:school_id} class="col-span-2 md:col-span-4">
          <SchoolInput
            staff_user={@staff_user}
            pupil_id={Changeset.get_field(@changeset, :pupil_id)}
            class="w-full"
            id="school_input"
          />
        </Field>
```

**Comment by msaraiva** [comment] 2022-07-21 13:00
Hi! 

I was able to create a test to reproduce this error. It seems those changes in LV broke the case when we have a stateful component inside a function component. Like:

```heex
  <.func>
    <StatefulComponent id="comp" />
  </.func>
```

Since `<Form>` is just a wrapper around `<.form>`, it stopped accepting live components through slots. I'll do some further investigation and try to fix it.

Thanks for reporting this issue.

**Comment by msaraiva** [comment] 2022-07-21 13:34
I just noticed that https://github.com/surface-ui/surface/pull/609 (which has already been merged into `main`) apparently fixes this issue too. Can any of you confirm that? In case it works, I'll try to apply those changes to the `v0.7` branch and release a new patch version.

**Comment by elliotb** [comment] 2022-07-21 15:01
@msaraiva Thanks, I can confirm that using `main` resolves the issue in my case.

**Comment by msaraiva** [comment] 2022-07-21 15:13
I just released `v0.7.5` which should fix this. Please let me know if you still find any issue.

Thanks!

**Closed by msaraiva** 2022-07-21 15:13 UTC

**Comment by elliotb** [comment] 2022-07-21 15:16
@msaraiva Fantastic, looks like v0.7.5 is working for us. Thanks for your support, and Surface in general!

**Comment by maennchen** [comment] 2022-07-21 17:25
@msaraiva My repo works as well now, thanks for the fix 😊
