### ISSUE TITLE
Improve prop validation

### ISSUE THREAD

**Issue by Andrew0914** [surface-ui/surface#451] opened 2021-07-05 20:09 UTC
## Describe the bug

I just started play around with surface v0.5.0  and I created a simple component with a simple string required prop, but  it does not matter if I pass no value or invalid type value, It renders it without throwing any error.

## How to reproduce it

1. Create component that renders a simple text message
2. Declare a  message prop, its type: string and it is required
```elixir
 prop message, :string, required: true
```
3. Pass an integer
4. Pass nothing to the prop

My component: 
```elixir
defmodule PentoWeb.Pento.Title do
  use Surface.Component

  @doc "Someone to say hello to"
  prop message, :string, required: true

  def render(assigns) do
    ~F"""
    <h1>{ @message }</h1>
    """
  end
end
```

Where I am using it
```elixir
defmodule PentoWeb.Pento.GameLive do
  use Surface.LiveView
  alias PentoWeb.Pento.Title

  def mount(_params, _session, socket), do: {:ok, socket}

  def render(assigns) do
    ~F"""
    <section class="container">
      <Title />
    """
  end
end
```

## The behavior you expected

If I am passing a no string value or even no value it has to throw and error because of the validations, but currently It renders without problem

## Your Environment
Surface: v0.5.0
LiveView: v0.15.1
Elixir: v1.11.2
Phoenix: v1.5.8

**Comment by Malian** [comment] 2021-07-06 16:51
Hi @Andrew0914 

Thanks for using Surface and reporting this.

Unfortunately, I am not able to reproduce the behaviour you described when the required property is not set. When I compile your code the following warning is printed in my terminal:

> warning: Missing required property "message" for component <PentoWeb.Pento.Title>
  lib/my_app_web/live/page_live/index.sface:3: MyAppWeb.PageLive.Index (module)

Could you please compile your project, and confirm me that the warning does not appear?

Regarding, the validation of the property when you pass an integer, I am able to reproduce it. I suspect this happens because the value passed to the prop should implement the `String.Chars` protocol which is the case with an `integer`.

@msaraiva I do not see any restriction to validate literal at compile time. It could be a nice addition. For example, we could raise a compile time error for the following code:

```elixir
<Title message={1} />
```

WDYT?

**Comment by davydog187** [comment] 2021-07-06 17:57
I personally love the idea of validating literals at compile-time and raising en error :)

**Comment by msaraiva** [comment] 2021-07-06 20:59
> I do not see any restriction to validate literal at compile time. It could be a nice addition. For example, we could raise a compile time error for the following code:
> 
> ```elixir
> <Title message={1} />
> ```
> 
> WDYT?

@Malian there's no restriction to support that, as far as I remember. We just haven't implemented it yet. I think I've recently discussed with @davydog187 about adding more compile-time validations for simple similar cases. Here are some that I remember:

* Validate literals against the prop types (as you pointed out), e.g., `<Title message={1} />`
* Validate forwarded assigns against the prop types, e.g., `<Title message={@an_integer_value} />`
* Validate literals against the list in the `values!` option of the prop.

One thing I'm not sure yet is how strict we should be on the `:string` type. Since phoenix can automatically render any value that implement the `String.Chars` protocol, by adding a more strict validation, we'll no longer allow passing any of those values without explicitly converting them using `to_string/1` (or anything similar). We could create another less strict type but I'm not sure if it could be even more confusing to users.

**Comment by Malian** [comment] 2021-07-07 10:00
> One thing I'm not sure yet is how strict we should be on the `:string` type. Since phoenix can automatically render any value that implement the `String.Chars` protocol, by adding a more strict validation, we'll no longer allow passing any of those values without explicitly converting them using `to_string/1` (or anything similar). We could create another less strict type but I'm not sure if it could be even more confusing to users.

@msaraiva not sure if I get the point. The user could always define the type as `:any`. Do you have a concrete example where being restrictive in a component will break phoenix without explicitly casting the value with `to_string` ?

**Comment by Andrew0914** [comment] 2021-07-07 12:02
> Hi @Andrew0914
> 
> Thanks for using Surface and reporting this with this amazing and complete bug report!
> 
> Unfortunately, I am not able to reproduce the behaviour you described when the required property is not set. When I compile your code the following warning is printed in my terminal:
> 
> > warning: Missing required property "message" for component <PentoWeb.Pento.Title>
> > lib/my_app_web/live/page_live/index.sface:3: MyAppWeb.PageLive.Index (module)
> 
> Could you please compile again your project (remove the _build folder), and confirm me that the warning does not appear?
> 
> Regarding, the validation of the property when you pass an integer, I am able to reproduce it. I suspect this happens because the value passed to the prop should implement the `String.Chars` protocol which is the case with an `integer`.
> 
> @msaraiva I do not see any restriction to validate literal at compile time. It could be a nice addition. For example, we could raise a compile time error for the following code:
> 
> ```elixir
> <Title message={1} />
> ```
> 
> WDYT?

You are right @Malian  the warning is shown when the required property is not presented ✔️ 

But yeah, when you pass this

```elixir
<Title message={1} />
```

there is no warning and it could be a nice addition get a warning or error at compilation time.

**Comment by msaraiva** [comment] 2021-07-07 13:25
> The user could always define the type as `:any`. Do you have a concrete example where being restrictive in a component will break phoenix without explicitly casting the value with `to_string` ?

@Malian currently, there's no special validation for type `:string`. It's mostly just an annotation, which means it is handled by the default type handler, making it equivalent to type `:any`. 

The default handler just checks at runtime if the value implements `String.Chars`, i.e., it will accept a large range of types, including `binary`, `iolist`, `iodata`, `integer`, `atom`, `Date`, `DateTime` and so on, as you can see here: https://github.com/surface-ui/surface/blob/ec6ec43be330074c9f5851c230ffc2025dad6a87/lib/surface/type_handler/default.ex#L47

If we start raising errors on something like `a_prop_of_type_string={@an_iolist_value}`, we introduce a breaking change. I'm not saying it's a bad idea but we just need to keep in mind that whenever we add validation, we may break existing code or make the validation inconsistent. 

For instance, if we validate string literals at compile-time, it will no longer accept `message={1}` but it will accept `message={a_func_returning_1()}` without any warning whatsoever, after all, the `String.Chars` is implemented for `integer` values and if you inject it in the template using `{@message}`, it will be rendered just fine.

To avoid that inconsistence, we may have to validate the value at runtime too. The question is: If we do that, should we provide another less strict type for values implementing `String.Chars`? Or should we force the user to go with `:any`? I'm sure users like @miguel-s will hate to be forced to use `:any` :)

**Comment by msaraiva** [comment] 2021-07-07 13:34
BTW, we should probably review all similar compile-time validations we have for prop types and make sure we validate the value at both, compile-time and runtime.

**Comment by Malian** [comment] 2021-07-07 14:10
Thanks for the clarification, I wasn't thinking of adding validation at runtime but only at compilation time. Not sure we should validate at runtime 🤔

Finally, I am even wondering if we should validate at compile-time string type if the value implements the `String.Chars` protocol. That being said, it is clear for integers that they can be converted to a string, but I have always found it weird for `list` for example, see #450 and #449 ^^ Afterall, Elixir is a dynamic language 😁 

After few minutes of reflection, I am in favour of validating that the value implements the `String.Chars` protocol instead of having a strong validation.

**Comment by msaraiva** [comment] 2022-07-29 13:20
I'm closing this as we'll rely mostly on LV's own attribute validations from `v0.18` on.

**Closed by msaraiva** 2022-07-29 13:20 UTC
Labels: enhancement
