### ISSUE TITLE
<Checkbox> click triggered twice when inside of <Label> tag

### ISSUE THREAD

**Issue by margusp2heathmont** [surface-ui/surface#528] opened 2021-11-09 11:37 UTC
Expected behaviour: toggles value
Real result: sometimes is leaves the same, sometimes it toggles

```
<Form for={@changeset}>
  <Label field={:name}>
    <Checkbox field={:name}>
   Some text
  </Label>
</Form>
```

**Comment by Malian** [comment] 2021-11-10 13:23
@margusp2heathmont Thanks for opening an issue.

Could you please provide us a minimal working application that reproduces the bug. I am not able to reproduce it locally.

From my side, when I click on the label, or the checkbox, everything works as expected. It toggles only once.

Thanks

**Comment by Malian** [comment] 2021-11-18 14:55
@margusp2heathmont I am closing the issue. Feel free to reopen it needed.

**Closed by Malian** 2021-11-18 14:55 UTC
