### ISSUE TITLE
Context not preserved through function calls

### ISSUE THREAD

**Issue by zachdaniel** [surface-ui/surface#267] opened 2021-02-09 20:09 UTC
Given this example component:
```elixir
defmodule TestComponent do
  use Surface.Component

  alias Surface.Components.Context

  def render(assigns) do
    ~H"""
    <div>
      <Context put={{ __MODULE__, name: "world" }}>
        <Context get={{ __MODULE__, name: name }}>
          Hello {{name}}!
        </Context>

        {{render_hello(assigns)}}
      </Context>
    </div>
    """
  end

  def render_hello(assigns) do
    ~H"""
    <div>
      <Context get={{ __MODULE__, name: name }}>
        Hello {{name}}!
      </Context>
    </div>
    """
  end
end
```

What is ultimately rendered into the page is:
```
Hello world!
Hello !
```

------

As you can see, the same code snippet used outside of a function call has access to the context, but when used inside of a function call it does not.

Versions:

Surface: 0.2.1
Phoenix: 1.5.7
LiveView: 0.15.4
Elixir: 1.11.2
Erlang: 23

**Comment by Malian** [comment] 2021-03-21 12:58
I can reproduce the bug.

@msaraiva Not sure if it is a bug or the normal behavior when a function is called directly. I lean towards the second suggestion.

I understand that it is strange from a developer point of view that it works  if the `render_hello` function is extracted in its own component.

```elixir
defmodule SubTestComponent do
  use Surface.Component

   def render(assigns) do
    ~H"""
    <div>
      <Context get={{ __MODULE__, name: name }}>
        Hello {{name}}!
      </Context>
    </div>
    """
  end   
end

defmodule TestComponent do
  use Surface.Component

  alias Surface.Components.Context

  def render(assigns) do
    ~H"""
    <div>
      <Context put={{ __MODULE__, name: "world" }}>
        <Context get={{ __MODULE__, name: name }}>
          Hello {{name}}!
        </Context>

        {{render_hello(assigns)}}
        <SubTestComponent />
      </Context>
    </div>
    """
  end

  def render_hello(assigns) do
    ~H"""
    <div>
      <Context get={{ __MODULE__, name: name }}>
        Hello {{name}}!
      </Context>
    </div>
    """
  end 
end
```

Renders
```
Hello world!
Hello !
Hello world!
```

Not sure if we should handle this case, and if so, after a few investigation I do not know how.

**Comment by zachdaniel** [comment] 2021-03-21 13:26
Some context on why this is necessary for me: I have a recursive component and, AFAIK, that requires using functions because there is a compile-time dependency on any component you render, so you can't do something like `<__MODULE__ />` or `<This.Module.Name/>`

**Comment by Malian** [comment] 2021-03-21 14:00
@zachdaniel thanks for the additional pieces of information. Indeed currently Surface does not allow using a component recursively and usually, we recommend moving the recursion to a separate function as you did.

Could I ask you why you need `Context` in your use case? I am wondering why you do not pass the required value as a function argument?

**Comment by zachdaniel** [comment] 2021-03-21 14:03
The function was rendering a form input, and I was originally wrapping it in `FieldContext`, thinking that would set the field, but now I'm just passing it in as function arguments as you mentioned (which was the workaround to this).

**Comment by lnr0626** [comment] 2021-03-22 22:18
> Not sure if it is a bug or the normal behavior when a function is called directly. I lean towards the second suggestion.

This is a case of working as expected, but also not the best DX - this same issue has come up a few times

**Comment by msaraiva** [comment] 2021-03-23 13:05
I'm closing this since it's the expected behaviour and there's currently no consistent solution for it. However, we'll be able to provide a nice solution very soon when we introduce the new `component` macro in LV which will be called under the hood when using something like:

```
<#my_func />
```

The goal is to have lightweight stateless components defined as functions. By calling a function with that syntax will not only enable diff tracking for the returned content but will also allow us to decorate the underlying call to the `component` macro, just like we currently do for the `live_comonent` call.

**Closed by msaraiva** 2021-03-23 13:05 UTC
