### ISSUE TITLE
sface file parser is not treating TAB as whitespace

### ISSUE THREAD

**Issue by derek-zhou** [surface-ui/surface#322] opened 2021-03-31 20:21 UTC
I am using surface 0.3.2 with separate sface files. The sface file parsing is sensitive about line breaks and white space, for example this does not work:
``` html
<div>
    <Form for={{ :login }}
          submit="submit">
    </Form>
</div>
```
But this works:
``` html
<div>
    <Form for={{ :login }} submit="submit">
    </Form>
</div>
```

**Comment by Malian** [comment] 2021-04-01 11:01
Hi @derek-zhou !

I am not able to reproduce the bug. Could you please share with us the error that occurred? Best, could you create a minimal application that reproduces the bug?

Thanks!

**Comment by derek-zhou** [comment] 2021-04-01 15:42
The error it gives:
```
== Compilation error in file lib/liv_web/live/test.ex ==
** (Surface.Compiler.ParseError) lib/liv_web/live/test.sface:2: expected closing tag for "Form"
    (surface 0.3.2) lib/surface/compiler.ex:113: Surface.Compiler.compile/5
    (surface 0.3.2) expanding macro: Surface.Renderer.__before_compile__/1
    lib/liv_web/live/test.ex:1: Test (module)
    (elixir 1.11.4) lib/kernel/parallel_compiler.ex:314: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

I debug it a little and it seems to be related to `\t` in code. In the example I cited above, the new line of `submit="submit">` is indented by `\t`, not just spaces. the `\t` was lost when I copied the code into github. 

So I think the sface parser is not treating `\t` properly (as wwhitespace). If you still cannot reproduce please let me know; I will put up a minimal case.

**Comment by derek-zhou** [comment] 2021-04-01 15:52
in 
https://github.com/surface-ui/surface/blob/ed77d6b359ef29df9dabf78b147301ac04dad17c/lib/surface/compiler/parser.ex#L115

Shouldn't it be: `[?\s, ?\t, ?\r, ?\n]`?

**Comment by msaraiva** [comment] 2021-04-01 16:02
Yup. It actually should be the same as: https://github.com/surface-ui/surface/blob/ed77d6b359ef29df9dabf78b147301ac04dad17c/lib/surface/compiler/helpers.ex#L146

Thanks for tracking down the problem!

**Comment by msaraiva** [comment] 2021-04-01 18:39
BTW, @derek-zhou, in case you want to work on a PR for this, feel free to do it. If so, let us know if you run into any trouble. Otherwise, I'll fix it sometime tomorrow. Cheers.

**Comment by derek-zhou** [comment] 2021-04-01 19:09
Please go ahead. If I found something more involved I will do PR the next time.

**Comment by msaraiva** [comment] 2021-04-03 02:21
Fixed in https://github.com/surface-ui/surface/commit/a8a7af67b87f3197033c97f5c875269ccdf28f8f.

**Closed by msaraiva** 2021-04-03 02:21 UTC
