### ISSUE TITLE
Co-located JS hook files being copied on each page load in development

### ISSUE THREAD

**Issue by harmon25** [surface-ui/surface#291] opened 2021-03-13 00:12 UTC
I am using a few co-located hooks in Surface v0.3.1, and it appears that loading the page via live_redirect or full reload always copies the hook files to the assets directory (because it is re-compiling?). 

This is triggering webpack to rebuild assets despite the hook file(s) not having changed, but I am guessing it was copied again. 

The project is leveraging webpack5, which might be a factor - but don't think it should be 🤷

**Comment by msaraiva** [comment] 2021-03-13 15:09
Hi @harmon25! I've confirmed the issue. Working on it!

**Comment by harmon25** [comment] 2021-03-13 16:43
Thanks @msaraiva! 
This script might help:

```sh
#!/bin/bash 

inotifywait -m ./assets/js/_hooks -e create,modify |
    while read dir action file; do
        echo "The file '$file' appeared in directory '$dir' via '$action'"
    done
```

**Comment by harmon25** [comment] 2021-03-13 18:07
Just tested the fix, it does the trick.

You are amazing, thanks again! 👍

**Comment by msaraiva** [comment] 2021-03-13 18:19
@harmon25 this PR also fixes a couple of other edge cases I found while testing. After this gets merged, I need to change the docs to instruct people to add the compiler after the default ones. So instead of:

```
  def project do
    [
      ...,
      compilers: [:surface, :phoenix] ++ Mix.compilers(),
      ...
    ]
  end
```

it should be:

```
  def project do
    [
      ...,
      compilers: [:phoenix] ++ Mix.compilers() ++ [:surface],
      ...
    ]
  end
```

Otherwise, it fails when compiling for the first time or after a `mix clean` because the project's application doesn't exist yet.

**Closed** 2021-03-14 04:08 UTC
